### ISSUE TITLE
poreFUME test fail

### ISSUE THREAD

**Issue by gaarangoa** [EvdH0/poreFUME#1]
Hi poreFUME developers, we are trying to use your code for analyzing some samples. But, after running everything as is explained in the INSTALL file, we are not able to get it installed properly. Most of the tests are failed. We are trying to install it in ubuntu 14.04

thanks

**Comment by EvdH0** [comment]
Hi Gustavo,

Could you copy-paste the results from the test (`nosetests -v`) ?

**Comment by gaarangoa** [comment]
Hi Eric, 

I update some packages  and I got now almost all the tests except one. Here is the output of nosetests -v

Thanks so much for the help

gustavo1@farix:~/tools/poreFUME$ nosetests -v
test this ... ERROR
testCARDavialable (test.TestCARD) ... ok
testInputavialable (test.TestCARD) ... ok
testSegments (test.TestCARD) ... ok
testBLASTDATABASE (test.TestDependencies) ... ok
testBLASTN (test.TestDependencies) ... ok
testDBdust (test.TestDependencies) ... ok
testDBsplit (test.TestDependencies) ... ok
testF2DB (test.TestDependencies) ... ok
testLAcat (test.TestDependencies) ... ok
testPOA (test.TestDependencies) ... ok
testParallel (test.TestDependencies) ... ok
testSamtools (test.TestDependencies) ... ok
testbwaVersion (test.TestDependencies) ... ok
job ranger returns index of begin and end of job range. ... ok
testOverlap (test.TestFunctions) ... ok

======================================================================
ERROR: test this
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gustavo1/tools/poreFUME/test.py", line 29, in testBlast
    returnDF = poreFUME.blastDatabase(os.path.join('test','data','CblA_barcode48.fasta'),os.path.join('test','data','n.fasta.protein.homolog.fasta'),args)
  File "/home/gustavo1/tools/poreFUME/poreFUME.py", line 624, in blastDatabase
    raise RuntimeError('BLAST did not produce an alignment, one can implement an exception here. But for now stop')
RuntimeError: BLAST did not produce an alignment, one can implement an exception here. But for now stop
-------------------- >> begin captured logging << --------------------
root: INFO: Start builing blast database
root: INFO: 

Building a new DB, current time: 02/08/2017 10:08:32
New DB name:   test/data/n.fasta.protein.homolog.fasta
New DB title:  test/data/n.fasta.protein.homolog.fasta
Sequence type: Nucleotide
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 2181 sequences in 0.158335 seconds.

root: INFO: Start BLASTing for subsample test/data/CblA_barcode48.fasta
root: INFO: 
root: ERROR: USAGE
  blastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-perc_identity float_value] [-xdrop_ungap float_value]
    [-xdrop_gap float_value] [-xdrop_gap_final float_value]
    [-searchsp int_value] [-max_hsps_per_subject int_value] [-penalty penalty]
    [-reward reward] [-no_greedy] [-min_raw_gapped_score int_value]
    [-template_type type] [-template_length int_value] [-dust DUST_options]
    [-filtering_db filtering_database]
    [-window_masker_taxid window_masker_taxid]
    [-window_masker_db window_masker_db] [-soft_masking soft_masking]
    [-ungapped] [-culling_limit int_value] [-best_hit_overhang float_value]
    [-best_hit_score_edge float_value] [-window_size int_value]
    [-off_diagonal_range int_value] [-use_index boolean] [-index_name string]
    [-lcase_masking] [-query_loc range] [-strand strand] [-parse_deflines]
    [-outfmt format] [-show_gis] [-num_descriptions int_value]
    [-num_alignments int_value] [-html] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-remote] [-version]

DESCRIPTION
   Nucleotide-Nucleotide BLAST 2.2.28+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Unknown argument: "max_hsps"

root: INFO: Finished BLASTing for subsample test/data/CblA_barcode48.fasta
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 16 tests in 0.899s

FAILED (errors=1)

**Comment by EvdH0** [comment]
It seems the test is failing on BLAST
```
root: ERROR: USAGE
blastn
```
Are you sure you have version 2.4.0 installed from
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.4.0/ncbi-blast-2.4.0+-x64-linux.tar.gz ?
you can check by running `blastn -version`

**Comment by gaarangoa** [comment]
Just updated blast and run without problem!! thanks

**Comment by gaarangoa** [comment]
Hi Eric, 

I'm running poreFUME in our data and we got this error after start nanocorrect:
 
2017-02-15 14:42:22,157 - root -  ERROR - the nanocorrect python script gave the following error while parsing barcode: 1.  [fai_load] build FASTA index.

Thanks!
Gustavo

**Comment by EvdH0** [comment]
Hi Gustavo,

The error is generated [here](https://github.com/EvdH0/poreFUME/blob/0144d743dd5e3c99be92af9f4b5e81269f04930f/poreFUME.py#L504) and is thrown by nanocorrect, which in turn invokes DALIGNER.
Could you check  you actually have reads in the first barcode folder? ```output/barcode/{mySample}/1/``` ?

**Comment by Amitbioinfo** [comment]
Hello Eric,

I am trying to implement poreFUME pipeline to analyze our data. After installing everything as mentioned. I tried nosetests -v.

output is:
amit:poreFUME apple$ nosetests -v
----------------------------------------------------------------------
Ran 0 tests in 0.065s

OK

Then I read some where and tried 

amit:poreFUME apple$ nosetests test.py
......FFF....F..
======================================================================
FAIL: testDBdust (test.TestDependencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/apple/poreFUME/test.py", line 73, in testDBdust
    self.assertTrue(poreFUME.cmdExists('DBdust'))
AssertionError: False is not true

======================================================================
FAIL: testDBsplit (test.TestDependencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/apple/poreFUME/test.py", line 70, in testDBsplit
    self.assertTrue(poreFUME.cmdExists('DBsplit'))
AssertionError: False is not true

======================================================================
FAIL: testF2DB (test.TestDependencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/apple/poreFUME/test.py", line 67, in testF2DB
    self.assertTrue(poreFUME.cmdExists('fasta2DB'))
AssertionError: False is not true

======================================================================
FAIL: testbwaVersion (test.TestDependencies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/apple/poreFUME/test.py", line 88, in testbwaVersion
    self.assertTrue(stderr.split('\n')[2].split(': ')[1].rstrip() == '0.7.15-r1142-dirty')
AssertionError: False is not true

----------------------------------------------------------------------
Ran 16 tests in 5.315s

FAILED (failures=4)

I am trying to install it in Apple (mac-os). Will you please suggest solution for this. 

Thanks

**Comment by Amitbioinfo** [comment]
Hi Eric,

Simultaneously, apart from certain FAILURE as mentioned above, I tried to use it, 
First, I got some python - IndentationError and else/print syntax error, which I have solved by doint minute editing in the python script (don't know possible reasons of error, may be they are system dependent)

In our case, we have pooled data but not having barcode files, because of that I wanted to use 
**--skipDemux option**  but the pipeline is not allowing. So what could be the possible solution for this. Can you please provide suggestion for this. 

Thank you in advance.
Amit

**Comment by EvdH0** [comment]
Hi @Amitbioinfo 

Did you try running ```install.sh``` as written in https://github.com/EvdH0/poreFUME/blob/master/INSTALL.md ?
Because from your errors it seems that you are missing parts of DAZZ_DB which should be installed automatically by ```install.sh```, same goes for bwa which is installed by ```install.sh```. 
In case these programs are installed, check wether they are in your path. Otherwise run ```. env.sh```

**Comment by Amitbioinfo** [comment]
Hi Eric,

Thank you for reply. Yes I used and run install.sh and env.sh. But somehow, everything installed but these are not in the path. Now I exported paths and its not showing any failure but also is not showing output as mentioned in README

After running ....
amit:poreFUME apple$ nosetests test.py
................
----------------------------------------------------------------------
Ran 16 tests in 6.150s

OK

**Comment by EvdH0** [comment]
@Amitbioinfo that output looks correct. When you run with the ```-v``` flag you will see the full output. So ```nosetests -v```

**Comment by Amitbioinfo** [comment]
Hello,

In our case, we have pooled data but not having barcode files, because of that I wanted to use
--skipDemux option but the pipeline is not allowing. So what could be the possible solution for this. Can you please provide suggestion for this.

Thank you in advance.
Amit

**Comment by EvdH0** [comment]
@Amitbioinfo 
This would not be a typical use case of poreFUME and it would be better to just run nanocorrect (which is deprecated http://simpsonlab.github.io/2016/02/25/deprecating-nanocorrect/) and nanopolish separately. However in case you want to proceed; run with ```--skipDemux --skipDemuxCollect```. As stated in the help file:
> Skip the barcode demux step and proceed with nanocorrect, cannot be used with overwrite. Assumes the output/barcode/ and output/ directory are populated accordingly

So you should have in your poreFUME directory the following structure/file:
```output/barcode/{samplename}/1.{samplename}.afterBC.fasta```
